title: Brains, Machines and Modern Times
description: "Some of what I find interesting about (you guessed it) brains, machines, and modern times"
theme: minima

# contact info for footer
email: amr.a.aboshaisha@gmail.com
github_username: aaboshaisha